export function getRandomItem(array) {
  return array[Math.floor(Math.random() * array.length)];
}

// Truth questions
export const truths = [
    "What's the most embarrassing thing you've ever done in public?",
      "Have you ever lied to your best friend? What was it about?",
      "What’s the worst thing you’ve done to someone and regretted it?",
      "Who was your first crush and how did you feel about them?",
      "Have you ever had a secret crush on someone in this room?",
      "What’s something you’ve never told anyone?",
      "What’s the most embarrassing thing on your phone?",
      "Have you ever had a crush on a teacher?",
      "Who was your first kiss, and where did it happen?",
      "What’s the biggest lie you’ve ever told your parents?",
      "Have you ever cheated on a test or exam?",
      "What’s the most awkward situation you’ve been in?",
      "Have you ever stolen something?",
      "Who is the last person you searched for online?",
      "Have you ever been in love?",
      "What’s one thing you’ve never told anyone because you were too embarrassed?",
      "Have you ever had a crush on someone you shouldn’t have?",
      "What’s the most childish thing you still do?",
      "What’s the worst date you’ve ever been on?",
      "Have you ever kissed someone of the same sex?",
      "Who is your secret celebrity crush?",
      "What’s the most embarrassing thing your parents have caught you doing?",
      "Have you ever lied about your age?",
      "Have you ever sneaked out of the house?",
      "What’s the most awkward text you’ve sent?",
      "What’s the biggest mistake you’ve ever made in a relationship?",
      "Have you ever been caught doing something you shouldn’t have?",
      "What’s the most ridiculous thing you’ve ever done for love?",
      "Who was the last person you texted, and what was the message about?",
      "Have you ever had a crush on someone who didn’t know you existed?",
      "What’s the worst thing you’ve said about someone behind their back?",
      "What’s the most embarrassing thing that’s ever happened to you at school?",
      "Have you ever lied about where you were going or who you were with?",
      "What’s the most embarrassing outfit you’ve ever worn?",
      "Have you ever been caught in a lie?",
      "What’s the worst thing you’ve done when you were angry?",
      "Have you ever broken someone’s heart?",
      "What’s the most embarrassing thing in your search history?",
      "Have you ever sent a text to the wrong person?",
      "What’s the biggest secret you’ve kept from your parents?",
      "What’s the most embarrassing photo of you online?",
      "Have you ever regretted dating someone?",
      "Who do you think is the most attractive person in this room?",
      "What’s the most embarrassing thing that’s happened to you during a Zoom meeting or call?",
      "Have you ever pretended to like something just to fit in?",
      "What’s the worst thing you’ve said to a friend?",
      "Have you ever lied to your parents about where you were?",
      "Have you ever made a prank call?",
      "Have you ever had a crush on a friend’s sibling?",
      "What’s the most embarrassing thing you’ve said to someone you liked?",
      "Who is the last person you stalked on social media?",
      "Have you ever pretended to be sick to avoid going somewhere?",
      "What’s the most embarrassing thing you’ve done on a video call?",
      "Have you ever blamed someone else for something you did?",
      "What’s one thing you’d change about yourself?",
      "Have you ever had a crush on someone older than you?",
      "What’s something you’ve done that you’d never want your parents to find out?",
      "Have you ever kissed someone in this room?",
      "Have you ever lied to get out of doing something?",
      "Have you ever been caught sneaking out of the house?",
      "What’s the most embarrassing song on your playlist?",
      "Have you ever ghosted someone you were talking to?",
      "Have you ever told a lie that turned into a big situation?",
      "Have you ever fallen asleep in class or a meeting?",
      "What’s the biggest secret you’ve kept from your best friend?",
      "What’s the most embarrassing thing you’ve ever done on social media?",
      "Have you ever been caught in a lie by someone you trusted?",
      "What’s the weirdest thing you’ve ever done to impress someone?",
      "Have you ever been in a love triangle?",
      "What’s the most embarrassing nickname you’ve ever had?",
      "Have you ever been caught in a lie at school or work?",
      "What’s something you’ve done that you would never do again?",
      "What’s your guilty pleasure TV show or movie?",
      "Have you ever lied about your relationship status to someone?",
      "What’s the weirdest food you’ve ever tried?",
      "Have you ever stalked someone on social media?",
      "What’s one thing you’ve done that you never want anyone to know about?",
      "Have you ever sent a screenshot of a conversation to the wrong person?",
      "What’s something you’ve done for attention?",
      "Have you ever been in a situation where you had to pretend you knew what you were doing?",
      "What’s the most embarrassing thing you’ve done in front of your crush?",
      "What’s a habit you have that you don’t want anyone to know about?",
      "Have you ever lied about a relationship just to avoid awkward questions?",
      "What’s one thing you would never want to happen to you in public?",
      "Have you ever lied to make yourself look cooler?",
      "What’s something that always makes you laugh no matter how many times you see it?",
      "Have you ever been caught talking about someone behind their back?",
      "What’s the weirdest dream you’ve ever had?",
      "Have you ever skipped school or work for no reason?",
      "What’s the most embarrassing thing you’ve done at a family gathering?",
      "What’s the most embarrassing thing you’ve done at a party?",
      "Have you ever lied to a teacher or boss?",
      "What’s the strangest thing you’ve ever eaten for breakfast?",
      "Have you ever made a fool of yourself in front of someone you liked?",
      "Have you ever sent a message to someone and then immediately regretted it?",
      "What’s the most awkward text message you’ve ever sent to someone?",
      "What’s something you secretly find hilarious but never tell anyone?",
      "Have you ever been caught talking about someone behind their back?",
      "What’s the most embarrassing thing you’ve said on a first date?",
      "What’s the weirdest rumor you’ve ever heard about yourself?"
    // ... (all your truth questions)
  ];
  
  // Dare challenges
  export const dares = [
    "Try to talk like a pirate for 2 minutes and send me the video.",
            "Eat a piece of food blindfolded and record yourself doing it.",
            "Pretend you're a penguin and waddle for 30 seconds on camera.",
            "Do the moonwalk for 30 seconds and send a video.",
            "Imitate your favorite animal for 1 minute and send a voice note.",
            "Wrap your face with toilet paper like a mummy and take a selfie.",
            "Pretend you’re in a race and run around your house for 30 seconds.",
            "Try to say a tongue twister in reverse and send me the clip.",
            "Act like a robot and send me the video.",
            "Do a silly face for a minute and screenshot it.",
            "Try to recite the alphabet backward and send a voice note.",
            "Do 10 squats while saying a tongue twister and share a video.",
            "Make an animal noise for 1 minute and send me a voice note.",
            "Post a picture with a funny face and tag me.",
            "Dance like no one's watching for 30 seconds and post a story.",
            "Talk in rhymes for 2 minutes and send the video.",
            "Imitate your favorite celebrity and send a video.",
            "Do your best superhero impression and share the clip.",
            "Pretend you're a chef and describe a recipe for 1 minute.",
            "Act like you're in a movie scene and send me the video.",
            "Record yourself singing a song you don’t know and send it.",
            "Give a weather forecast for your area in 30 seconds.",
            "Pretend you’re stuck in a box for 1 minute and record it.",
            "Record a rap about something random and send it.",
            "Do your best magic trick and record it.",
            "Draw a silly picture and send it to the group.",
            "Pretend you’re a famous singer and sing into a hairbrush.",
            "Do your best dance move and share it with the group.",
            "Speak in a different accent for 2 minutes and send a clip.",
            "Imitate a famous movie quote and send it as a video.",
            "Pretend you're an alien visiting Earth for the first time.",
            "Create a silly product and make a 30-second ad for it.",
            "Post something random on your story and leave it for 1 hour.",
            "Change your profile pic to something random for 1 hour.",
            "Do an impression of a famous person and send the video.",
            "Imitate a famous YouTuber and send the clip.",
            "Send a random emoji to someone and see their reaction.",
            "Share the weirdest thing you've ever Googled.",
            "Do 5 cartwheels in a row and record it.",
            "Post a dance routine in slow motion and tag me.",
            "Talk in a high-pitched voice for 2 minutes and send a video.",
            "Do a dramatic reading of a text message and send the video.",
            "Pretend to be a news anchor and read a random headline.",
            "Tell a random joke and see who laughs first.",
            "Wear socks on your hands and record a video.",
            "Record yourself singing in a funny voice and post it.",
            "Act like a robot for 1 minute and send the video.",
            "Pretend you're a spy and sneak around while recording.",
            "Share your favorite meme and explain why it's so funny.",
            "Pretend to be a waiter and take a pretend order."
    // ... (all your dare challenges)
  ];